---
title: "Data Manipulation"
author: "Qinyao Wu"
date: "9/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


##Import FAS csv file

import first csv.

```{r}

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

##Select variable
by listing

```{r}
select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, pups_survive)
```

...by specifying a range:

```{r}
select(litters_data, gd_of_birth:pups_survive)
select(litters_data, group, gd_of_birth:pups_survive)
```

...by removing

```{r}
select(litters_data, -litter_number)
```


```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)
rename(litters_data, gest_day_0_weight = gd0_weight)
```

...use select helpers

```{r}
select(litters_data, starts_with("gd"))

select(litters_data, litter_number, starts_with("pup"))

select(litters_data, litter_number, everything())
```

select pups data

```{r}
select(pups_data, litter_number, sex, pd_ears)
```

##Filters observation

```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)

filter(litters_data, pups_born_alive == 8)

filter(litters_data, !is.na(gd0_weight))

filter(litters_data, group == "Low8" | group == "Low7")
filter(litters_data, group %in% c("Low7", "Low8"))

filter(litters_data, pups_born_alive %in% 4:6)

filter(litters_data, pups_born_alive %in% 4:7, !is.na(gd0_weight))
```

```{r}
filter(pups_data, sex == 1)
filter(pups_data, pd_walk < 11, sex == 2)
```

##Mutate
```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
  )

mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  wt_gain_squared = wt_gain^2
  )

#mutate(pups_data,
 # pd_pivot_minus = pd_pivot - 7,
  #pd_total = pd_ears + pd_eyes + pd_pivot + pd_walk
  #)

```

##Arrange


```{r}
arrange(litters_data, desc(pups_born_alive), gd0_weight)


```


```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = mutate(litters_data_selected_cols, 
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group))
litters_data_with_vars
```

Use nested function calls

```{r}
litters_data_clean = 
  mutate(
    select(
      janitor::clean_names(
        read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
        ), 
    -pups_survive
    ),
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
  )
litters_data_clean
```


##Use piping

```{r}
read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group)
  ) %>% 
  filter(.data = ., !is.na(gd0_weight))
```


Illustrate placeholder

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group)
  ) %>% 
  filter(.,!is.na(gd0_weight)) 

```







