---
title: "Data Manipulation"
author: "Qinyao Wu"
date: "9/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

PULSE DATA
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
```
this is not tidy yet

```{r}

pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data

pulse_tidy = gather(pulse_data, key = visit, value = bdi, bdi_score_bl:bdi_score_12m)
## Warning: attributes are not identical across measure variables;
## they will be dropped
pulse_tidy
```

```{r}
pulse_tidy %>%
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>%
  select(-bdi_str, -score_str) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"))%>%
  View
```
All together, the data import / cleaning pipeline is :

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m) %>%
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>%
  select(-bdi_str, -score_str) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"))
  
  
```





